[general]
id = "cs1-ff00_0_110-1"
config_dir = "/etc/scion"

[trust_db]
connection = "/share/cache/cs1-ff00_0_110-1.trust.db"

[beacon_db]
connection = "/share/cache/cs1-ff00_0_110-1.beacon.db"

[path_db]
connection = "/share/cache/cs1-ff00_0_110-1.path.db"

[tracing]
enabled = true
debug = true
agent = "172.17.0.1:6831"

[metrics]
prometheus = "172.20.0.20:30452"

[api]
addr = "172.20.0.20:31152"

[features]

[ca]
mode = "in-process"

[log.console]
level = "debug"
