[general]
  id = "brA"
  config_dir = "/etc/scion"

[features]
  experimental_scmp_authentication = true

[router]
  preferred_underlays = { udpip = "afxdp" }

[router.bfd]
  disable = true

[log.console]
  level = "debug"
