global:
  evaluation_interval: 1s
  external_labels:
    monitor: scion-monitor
  scrape_interval: 1s
scrape_configs:
- file_sd_configs:
  - files:
    - ASff00_0_110/prometheus/br.yml
    - ASff00_0_111/prometheus/br.yml
    - ASff00_0_112/prometheus/br.yml
  job_name: BR
- file_sd_configs:
  - files:
    - ASff00_0_110/prometheus/cs.yml
    - ASff00_0_111/prometheus/cs.yml
    - ASff00_0_112/prometheus/cs.yml
  job_name: CS
- file_sd_configs:
  - files:
    - ASff00_0_110/prometheus/disp.yml
    - ASff00_0_111/prometheus/disp.yml
    - ASff00_0_112/prometheus/disp.yml
  job_name: dispatcher
- file_sd_configs:
  - files:
    - ASff00_0_110/prometheus/sd.yml
    - ASff00_0_111/prometheus/sd.yml
    - ASff00_0_112/prometheus/sd.yml
  job_name: SD
